// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMovieDetails(arg1:number):Promise<main.Movie>;

export function GetSeasonEpisodes(arg1:number,arg2:number):Promise<Array<main.Episode>>;

export function GetShowDetails(arg1:number):Promise<main.Show>;

export function GetTrendingMovies():Promise<Array<main.Movie>>;

export function GetTrendingShows():Promise<Array<main.Show>>;

export function SearchMovie(arg1:string):Promise<Array<main.Movie>>;

export function SearchShow(arg1:string):Promise<Array<main.Show>>;
