// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMovieDetails(arg1) {
  return window['go']['main']['App']['GetMovieDetails'](arg1);
}

export function GetSeasonEpisodes(arg1, arg2) {
  return window['go']['main']['App']['GetSeasonEpisodes'](arg1, arg2);
}

export function GetShowDetails(arg1) {
  return window['go']['main']['App']['GetShowDetails'](arg1);
}

export function GetTrendingMovies() {
  return window['go']['main']['App']['GetTrendingMovies']();
}

export function GetTrendingShows() {
  return window['go']['main']['App']['GetTrendingShows']();
}

export function SearchMovie(arg1) {
  return window['go']['main']['App']['SearchMovie'](arg1);
}

export function SearchShow(arg1) {
  return window['go']['main']['App']['SearchShow'](arg1);
}
